config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('service.urls', namespace='service')),
    path('users/', include('users.urls', namespace='users')),
]

service/urls.py
from django.urls import path

from service.apps import ServiceConfig
from service.views import home, MailingCreateView, MailingUpdateView, MailingDeleteView, ClientCreateView, \
    MessageCreateView, MailingListView, disable_mailing, MailingLogList, MailingMessagesList, ClientListView

app_name = ServiceConfig.name

urlpatterns = [
    path('', home, name='home'),  # Домашняя страница
    path('create/', MailingCreateView.as_view(), name='create'),  # Страница создания рассылки
    path('update/<int:pk>', MailingUpdateView.as_view(), name='update'),  # Страница редактирования рассылки
    path('delete/<int:pk>', MailingDeleteView.as_view(), name='delete'),  # Страница удаления рассылки
    path('clients/create', ClientCreateView.as_view(), name='create_client'),  # Страница создания клиента для рассылки
    path('message/create', MessageCreateView.as_view(), name='create_message'),  # Страница создания сообщения рассылки
    path('mailings/', MailingListView.as_view(), name='mailings'),  # Страница с списком рассылок
    path('mailings/disable/<int:pk>', disable_mailing, name='disable'),  # Страница с отключением рассылки
    path('log/', MailingLogList.as_view(), name='log'),  # Страница с логами
    path('messages/', MailingMessagesList.as_view(), name='messages'),  # Страница с списком сообщений
    path('clients/', ClientListView.as_view(), name='clients')  # страница с списком клиентов
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import UserLoginView, UserLogoutView, UserRegisterView, UserUpdateView, activate_new_user, \
    UsersListView, block_user

app_name = UsersConfig.name


urlpatterns = [
    path('', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('activate/<int:pk>/', activate_new_user, name='activate'),
    path('users_list/', UsersListView.as_view(), name='users_list'),
    path('block_user/<int:pk>', block_user, name='block_user')
]

service/models.py
from django.db import models

from config import settings
from service.cron import send_mailing

# варианты периодичности рассылки (раз в день, в неделю, в месяц)
MAILING_PERIODICITY = [(1, 'раз в день'), (2, 'раз в неделю'), (3, 'раз в месяц')]

MAILING_STATUS = [(1, 'завершена'), (2, 'создана'), (3, 'запущена')]  # варианты статуса рассылки
NULLABLE = {'null': True, 'blank': True}  # для необязательного поля


class MailingMessage(models.Model):
    """Модель сообщение для рассылки"""

    title = models.CharField(max_length=100, verbose_name='Тема сообщения')  # Тема сообщения
    message = models.TextField(verbose_name='Тело сообщения')  # Тело сообщения
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE)

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

    def __str__(self):
        return self.title


class Client(models.Model):
    """Модель клиента сервиса рассылок (того кому будем отправлять)"""

    email = models.CharField(max_length=100, verbose_name='Email')  # контактный email
    name = models.CharField(max_length=100, verbose_name='Имя')  # имя
    surname = models.CharField(max_length=100, verbose_name='Фамилия')  # фамилия
    patronymic = models.CharField(max_length=100, verbose_name='Отчество')  # отчество
    comment = models.TextField(verbose_name='Комментарий', **NULLABLE)  # комментарий
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE)  # Владелец (ссылка)

    def __str__(self):
        return f'{self.surname} {self.name} {self.patronymic}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Mailing(models.Model):
    """Модель настройки для рассылки"""

    date_time = models.DateTimeField(verbose_name='Время рассылки')  # время рассылки
    periodicity = models.PositiveSmallIntegerField(choices=MAILING_PERIODICITY, default=1)  # Периодичность
    status = models.PositiveSmallIntegerField(choices=MAILING_STATUS, default=2)  # статус рассылки
    client = models.ManyToManyField(Client)  # клиент рассылки
    message = models.ForeignKey(MailingMessage, on_delete=models.CASCADE)  # сообщение для рассылки
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE)  # Владелец (ссылка)

    def __str__(self):
        return f'Рассылка на {self.date_time} с периодичностью {self.periodicity}. Статус {self.status}'


    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        permissions = [('can_view_mailings', 'can_view_mailings'),
                       ('can_disable_mailings', 'can_disable_mailings'),
                       ]


class MailingLog(models.Model):
    """Модель лог рассылки"""

    date_time = models.DateTimeField(auto_now_add=True)  # дата и время последней попытки (формируется автоматически)
    status = models.CharField(max_length=100, verbose_name='Статус попытки')  # статус попытки
    answer = models.CharField(max_length=100, verbose_name='Ответ сервера', **NULLABLE)  # ответ почтового сервера
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE)  # рассылка

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'


class Blog(models.Model):
    """Модель блога"""

    title = models.CharField(max_length=100, verbose_name='Заголовок')
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='image/', verbose_name='Изображение', **NULLABLE)
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров')
    published_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

service/forms.py
from django import forms

from service.models import Mailing


class MailingForm(forms.ModelForm):
    """Класс-представление для создания рассылки"""

    class Meta:
        model = Mailing

        fields = ('date_time', 'periodicity', 'client', 'message')

    def __init__(self, *args, **kwargs):
        """Стилизация формы"""
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

service/views.py
import random


from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.decorators.cache import cache_page
from django.views.generic import CreateView, UpdateView, DeleteView, ListView

from service.cron import send_email_tasks
from service.forms import MailingForm
from service.models import Mailing, Client, MailingMessage, Blog, MailingLog


@cache_page(60)
def home(request):
    """Домашняя страница с выводом списка всех созданных, но не проведенных рассылок"""
    posts = Blog.objects.all()  # получаем все статьи в блоге
    posts_for_context = []
    if len(posts) > 3:
        for i in range(3):
            number = random.randint(0, len(posts))
            posts_for_context.append(posts[number])
            print(posts[number])
    else:
        posts_for_context = posts
    # если у пользователя есть права
    if request.user.has_perm('service.can_disable_mailings'):
        mailing_list = Mailing.objects.filter(status=2 or 3)  # все активные или созданные рассылки
        mailing_all = Mailing.objects.all()  # все рассылки, созданные в сервисе

    else:
        mailing_list = Mailing.objects.filter(status=2 or 3, owner=request.user.pk)  # все активные или созданные рассылки пользователя
        mailing_all = Mailing.objects.filter(owner=request.user.pk)  # все рассылки пользователя

    count_clients = Client.objects.all()  # количество клиентов для рассылок
    context = {'object_list': mailing_list, 'title': 'Список активных рассылок',
               'count_active_mailings': len(mailing_list),
               'count_mailings': len(mailing_all),
               'posts': posts_for_context,
               'count_clients': len(count_clients)}  # создание контекста для передачи в render
    return render(request, 'service/home.html', context)


class MailingListView(ListView):
    """Класс-представление для вывода всех имеющихся рассылок"""
    model = Mailing
    template_name = 'service/mailings_list.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = 'Список всех рассылок'
        return context
    
    def get_queryset(self):
        """фильтрация всех рассылок, созданных текущим пользователем"""

        # Если у пользователя есть права на отключение любой рассылки
        if self.request.user.has_perm('service.can_disable_mailings'):
            return super().get_queryset()

        # Иначе пользователю доступны только созданные им рассылки
        else:
            return Mailing.objects.filter(owner=self.request.user.pk)


class MailingCreateView(CreateView, LoginRequiredMixin):
    """Класс-представление для создания рассылки"""
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('service:home')

    def form_valid(self, form):
        """Добавление в создаваемый продукт информации об авторизованном пользователе"""

        mailing = form.save()  # сохранение информации о созданной рассылке
        mailing.owner = self.request.user  # присваиваем атрибуту owner ссылку на текущего пользователя
        send_email_tasks()
        mailing.save()
        return super().form_valid(form)


class MailingUpdateView(UpdateView, LoginRequiredMixin):
    """Класс-представление для редактирования рассылки"""

    model = Mailing
    fields = ('date_time', 'periodicity', 'client', 'status', 'message')
    success_url = reverse_lazy('service:home')


class MailingDeleteView(DeleteView, LoginRequiredMixin):
    """Класс-представление для удаления рассылки"""

    model = Mailing
    success_url = reverse_lazy('service:home')


class ClientCreateView(CreateView, LoginRequiredMixin):
    """Класс-представление для создания клиента"""

    model = Client
    success_url = reverse_lazy('service:create')
    fields = ('email', 'name', 'surname', 'patronymic', 'comment')


class MessageCreateView(CreateView, LoginRequiredMixin):
    """Класс-представление для создания сообщения"""

    model = MailingMessage
    fields = ('title', 'message')
    success_url = reverse_lazy('service:create')


def disable_mailing(pk):
    """функция для отключения рассылок"""

    mailing_for_disable = Mailing.objects.get(pk=pk)
    mailing_for_disable.status = 1
    mailing_for_disable.save()
    return redirect(reverse('service:mailings'))


class MailingLogList(ListView, LoginRequiredMixin):
    """Класс-представление для вывода лога проведенных рассылок"""
    model = MailingLog

    def get_queryset(self):
        """Если пользователь имеет права суперпользователя, ему возвращаются логи по всем проведенным рассылкам,
        иначе только по рассылкам, созданным текущим авторизованным пользователем"""

        return MailingLog.objects.filter(mailing__owner=self.request.user)


class MailingMessagesList(ListView, LoginRequiredMixin):
    """Класс-представление для вывода списка сообщений, созданных в сервисе"""
    model = MailingMessage

    def get_queryset(self):
        """Если пользователь обладает правами суперпользователя, ему возвращаются все сообщения, созданные в системе,
        иначе только сообщения, созданные текущим авторизованным пользователем"""

        if self.request.user.is_superuser:
            return super().get_queryset()

        return MailingMessage.objects.filter(owner=self.request.user)


class ClientListView(ListView, LoginRequiredMixin):
    model = Client

    def get_queryset(self):
        """Если пользователь имеет права суперпользователя, ему возвращаются все клиенты, созданные в системе,
        иначе только клиенты, созданные текущим авторизованным пользователем"""

        if self.request.user.is_superuser:
            return super().get_queryset()
        return Client.objects.filter(owner=self.request.user)

service/templates/service/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AleksMailing</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h3 class="my-0 mr-md-auto font-weight-normal">AleksMailing</h3>
    <h3 class="my-0 mr-md-auto font-weight-normal">{{ user.name }}</h3>
    <h5 class="my-0 mr-md-auto font-weight-normal">Добро пожаловать в сервис рассылок AleksMailing</h5>
    <nav class="ms-6">
        {% if user.is_authenticated %}
            <a href="{% url 'service:create' %}" type="button" class="p-2 btn btn-outline-primary">Создать рассылку</a>
        {% endif %}
        <a class="p-2 btn btn-outline-primary" href="/">Главная</a>

        {% if user.is_authenticated %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile' %}">Профиль</a>
        {% else %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>
</div>
<body>
{% block content%}
{% endblock %}
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                AleksMailing
                <small class="d-block mb-3 text-muted">&copy; 2023 - {% now 'Y'%}</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'service:mailings' %}">Все рассылки</a></li>
                    {% if perms.users.can_view_users %}
                        <li><a class="text-muted" href="{% url 'users:users_list' %}">Пользователи сервиса</a></li>
                    {% endif %}
                    {% if  user.is_authenticated %}
                        <li><a class="text-muted" href="{% url 'service:clients' %}">Клиенты сервиса</a></li>
                        <li><a class="text-muted" href="{% url 'service:messages' %}">Сообщения</a></li>
                        <li><a class="text-muted" href="{% url 'service:log' %}">Лог рассылок</a></li>
                    {% endif %}
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Инструкция по использованию сервиса</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О сервисе</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

service/templates/service/client_form.html
{% extends 'service/base.html'%}

{% block content %}
<form method="post" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    Добавление клиента
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn-success">Сохранить</button>
            </div>
        </div>
    </div>
</form>

{% endblock %}

service/templates/service/client_list.html
{% extends 'service/base.html'%}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <p class="lead">{{ title }}</p>
    </div>
<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.name }} {{ object.surname }} {{ object.patronymic }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <h6>Email:</h6>
                        <li>{{ object.email }}</li>
                        <h6>Комментарий:</h6>
                        <li>{{ object.comment }}</li>
                    </ul>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

service/templates/service/home.html
{% extends 'service/base.html'%}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <p class="lead">{{ title }}</p>
    </div>
<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.date_time }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <h6>Клиенты:</h6>
                        <li>{{ object.client.all | join:", " }}</li>
                        <h6>Сообщение:</h6>
                        <li>{{ object.message }}</li>
                        <h6>Периодичность:</h6>
                         <li>{{ object.get_periodicity_display }}</li>
                        <h6>Статус:</h6>
                        <li>{{ object.get_status_display }}</li>
                    </ul>
                    {% if object.owner == user or user.is_superuser %}
                        <a href="{% url 'service:update' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-primary">Редактировать</a>
                        <a href="{% url 'service:delete' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-danger">Удалить</a>
                    {% elif perms.service.can_disable_mailings %}
                        <a href="{% url 'service:disable' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-danger">Отключить</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <p class="lead">Случайные статьи из блога</p>
</div>
<div class="container">
    <div class="row text-center">
        {% for post in posts %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ post.title }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <h6>Описание:</h6>
                        <li>{{ post.description }}</li>
                        <h6>Изображение:</h6>
                         <li>{{ post.image }}</li>
                        <h6>Количество просмотров:</h6>
                        <li>{{ post.views_count }}</li>
                        <h6>Дата создания:</h6>
                        <li>{{ post.published_at }}</li>
                    </ul>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

</div>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <p class="lead">Статистика сервиса</p>
    <h6>Количество активных рассылок:</h6>
        <li>{{ count_active_mailings }}</li>
    <h6>Общее количество рассылок:</h6>
        <li>{{ count_mailings }}</li>
    <h6>Количество уникальных клиентов для рассылок</h6>
        <li>{{ count_clients }}</li>
</div>

{% endblock %}

service/templates/service/mailing_confirm_delete.html
{% extends 'service/base.html'%}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Удаление рассылки</h1>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <form method="post">
        {% csrf_token %}
        Уверены что хотите удалить рассылку?
        <button type="submit" class="p-2 btn btn-outline-primary">Удалить рассылку</button>
    </form>
</div>
{% endblock %}

service/templates/service/mailing_form.html
{% extends 'service/base.html'%}

{% block content %}
<form method="post" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    Создание рассылки
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn-success">Сохранить</button>
            </div>
        </div>
    </div>
<nav class="ms-6">
<a href="{% url 'service:create_client' %}" type="button" class="p-1 btn btn-outline-primary">Добавить клиента</a>
<a href="{% url 'service:create_message' %}" type="button" class="p-1 btn btn-outline-primary">Добавить сообщение</a>
</nav>
</form>

{% endblock %}

service/templates/service/mailinglog_list.html
{% extends 'service/base.html'%}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <p class="lead">{{ title }}</p>
    </div>
<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Рассылка №{{ object.mailing.pk }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <h6>Дата:</h6>
                        <li>{{ object.date_time}}</li>
                        <h6>Статус:</h6>
                        <li>{{ object.status }}</li>
                        <h6>Ответ сервера:</h6>
                         <li>{{ object.answer }}</li>
                    </ul>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

service/templates/service/mailingmessage_form.html
{% extends 'service/base.html'%}

{% block content %}
<form method="post" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    Добавление сообщения
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn-success">Сохранить</button>
            </div>
        </div>
    </div>
</form>

{% endblock %}

service/templates/service/mailingmessage_list.html
{% extends 'service/base.html'%}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <p class="lead">{{ title }}</p>
    </div>
<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <h6>Сообщение:</h6>
                        <li>{{ object.message|slice:':100'  }}</li>
                    </ul>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

service/templates/service/mailings_list.html
{% extends 'service/base.html'%}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <p class="lead">{{ title }}</p>
    </div>
<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.date_time }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <h6>Клиенты:</h6>
                        <li>{{ object.client.all | join:", " }}</li>
                        <h6>Сообщение:</h6>
                        <li>{{ object.message }}</li>
                        <h6>Периодичность:</h6>
                         <li>{{ object.get_periodicity_display }}</li>
                        <h6>Статус:</h6>
                        <li>{{ object.get_status_display }}</li>
                    </ul>
                    {% if object.owner == user or user.is_superuser %}
                        <a href="{% url 'service:update' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-primary">Редактировать</a>
                        <a href="{% url 'service:delete' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-danger">Удалить</a>
                    {% elif perms.service.can_disable_mailings %}
                        <a href="{% url 'service:disable' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-danger">Отключить</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}