config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('service.urls', namespace='service')),
    path('users/', include('users.urls', namespace='users')),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import UserLoginView, UserLogoutView, UserRegisterView, UserUpdateView, activate_new_user, \
    UsersListView, block_user

app_name = UsersConfig.name


urlpatterns = [
    path('', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('activate/<int:pk>/', activate_new_user, name='activate'),
    path('users_list/', UsersListView.as_view(), name='users_list'),
    path('block_user/<int:pk>', block_user, name='block_user')
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from service.models import NULLABLE


class User(AbstractUser):
    """Модель пользователя"""
    username = None

    email = models.EmailField(unique=True, verbose_name='email')

    phone = models.CharField(max_length=35, verbose_name='номер телефона', **NULLABLE)  # номер телефона
    name = models.CharField(max_length=100, verbose_name='Имя')  # Имя пользователя
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        permissions = [('can_view_users', 'can_view_users'),
                       ('can_block_users', 'can_block_users')]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.core.mail import send_mail

from config import settings
from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')
        template_name = 'users/register.html'

    def __init__(self, *args, **kwargs):
        """Стилизация формы"""
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def save(self, commit=True):
        """смена у пользователя флага на неактивный и отправка на почту пользователя
        письма с ссылкой на активацию"""

        user = super().save()  # сохраение в переменной пользователя
        send_mail(subject='Активация',
                  message=f'Для активации профиля пройдите по ссылке - http://127.0.0.1:8000/users/activate/{user.id}/',
                  from_email=settings.EMAIL_HOST_USER,
                  recipient_list=[user.email])  # отправка письма на почту
        user.is_active = False  # смена флага на неактивный
        user.save()  # сохранение
        return user


class UserProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'phone', 'name')

    def __init__(self, *args, **kwargs):
        """Стилизация формы"""
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView

from users.forms import UserRegisterForm, UserProfileForm
from users.models import User


class UserLoginView(LoginView):
    template_name = 'users/login.html'


class UserLogoutView(LogoutView):
    pass


class UserRegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'


class UserUpdateView(UpdateView):
    model = User
    success_url = reverse_lazy('service:home')
    form_class = UserProfileForm

    def get_object(self, queryset=None):
        return self.request.user


class UsersListView(ListView):
    model = User

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = 'Список зарегистрированных пользователей сервиса'
        return context


def activate_new_user(request, pk):
    """Функция для активации нового пользователя"""
    user = get_user_model()  # получение модели пользователя
    user_for_activate = user.objects.get(id=pk)  # получение пользователя с нужным id
    user_for_activate.is_active = True  # смена флага у пользователя на True
    user_for_activate.save()  # сохранение
    return render(request, 'users/activate_user.html')


def block_user(request, pk):
    """Контроллер для управления активностью зарегистрированных в системе пользователей"""

    user_for_block = User.objects.get(id=pk)  # пользователь для блокировки

    # проверка статуса активности
    if user_for_block.is_active:
        user_for_block.is_active = False
    else:
        user_for_block.is_active = True

    user_for_block.save()

    return redirect(reverse('users:users_list'))  # перенаправление на страницу со списком пользователей

users/templates/users/activate_user.html
{% extends 'service/base.html' %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <h2>Поздравляем, вы успешно активировались на нашей платформе</h2>
        </div>
    </div>
    </form>


{% endblock %}

users/templates/users/login.html
{% extends 'service/base.html' %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Авторизация пользователя
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn-success">Войти</button>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </form>
    

{% endblock %}

users/templates/users/register.html
{% extends 'service/base.html' %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Регистрация пользователя
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn-success">Зарегистрироваться</button>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </form>

{% endblock %}

users/templates/users/user_form.html
{% extends 'service/base.html' %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    Редактирование профиля пользователя
                </h3>
            </div>
            <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn-success">Сохранить</button>
            </div>
        </div>
    </div>
    </form>
{% endblock %}

users/templates/users/user_list.html
{% extends 'service/base.html'%}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <p class="lead">{{ title }}</p>
    </div>
<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <h6>Email:</h6>
                        <li>{{ object.email }}</li>
                        <h6>Контактный телефон:</h6>
                        <li>{{ object.phone }}</li>
                        <h6>Имя пользователя:</h6>
                         <li>{{ object.name }}</li>
                        <h6>Статус в системе:</h6>
                        <li>{% if object.is_active %}
                                Активен
                            {% else %}
                                Заблокирован
                            {% endif %}
                        </li>
                    </ul>
                    {% if object != user %}
                        {% if object.is_active %}
                            <a href="{% url 'users:block_user' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-danger">Заблокировать</a>
                        {% else %}
                            <a href="{% url 'users:block_user' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-danger">Разблокировать</a>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

</div>
{% endblock %}